--ffmpeg-location "/path/to/binary"
#--js-runtimes "deno:/path/to/deno/"
--no-playlist

# download in parallel (higher might get banned)
--concurrent-fragments 4

# if downloading large playlists comment out extractor arg and uncomment -t sleep to avoid youtube rate limits
--extractor-arg "youtube:playback_wait=0"
#-t sleep

#--embed-subs

# embed-thumbnail and make it square
--embed-thumbnail
--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

# remove unwanted metadata
--parse-metadata ":(?P<meta_date>)"
--parse-metadata ":(?P<meta_description>)"
--parse-metadata ":(?P<meta_synopsis>)"
--parse-metadata ":(?P<meta_comment>)"
--parse-metadata ":(?P<meta_track>)"
--parse-metadata ":(?P<meta_genre>)"
--parse-metadata ":(?P<meta_album_artist>)"
--parse-metadata ":(?P<meta_disc>)"
--parse-metadata ":(?P<meta_show>)"
--parse-metadata ":(?P<meta_season_number>)"
--parse-metadata ":(?P<meta_episode_id>)"
--parse-metadata ":(?P<meta_episode_sort>)"
--parse-metadata ":(?P<meta_language>)"

# use artist if possible, otherwise set as channel
--parse-metadata "channel:(?P<meta_artist>.*)"
# keep only first artist
--parse-metadata "artist:^(?!NA$)(?P<meta_artist>[^,]+)"
#--parse-metadata "artist:^(?!NA$)(?P<meta_artist>.*)"

--embed-metadata
